apiVersion: v1
kind: ServiceAccount
metadata:
  name: yesonit-serviceaccount
  namespace: yesonit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: yesonit
  name: yesonit-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yesonit-rolebinding
  namespace: yesonit
subjects:
- kind: ServiceAccount
  name: yesonit-serviceaccount
  namespace: yesonit
roleRef:
  kind: Role
  name: yesonit-role
  apiGroup: rbac.authorization.k8s.io
