apiVersion: apps/v1
kind: Deployment
metadata:
  name: yesonit-accessmanager-deployment
  labels:
    app: yesonit-accessmanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yesonit-accessmanager
  template:
    metadata:
      labels:
        app: yesonit-accessmanager
    spec:
      containers:
      - name: yesonit-accessmanager
        image: josabana/yesonit-accessmanager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: yesonit-accessmanager-secret
              key: MONGO_URI
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: yesonit-accessmanager-secret
              key: SESSION_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"