apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yesonit-accessmanager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yesonit-accessmanager-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50